<h3 class="col-12">Éditer un produit</h3>

<p class="col-12">Produit n°<?= $productData['id'] ?></p>

<form class=form2 action="<?= $requestUrl; ?>/admin/editproduct" method="post">

    <fieldset>
        <legend>Produit</legend>
        <input type="hidden" name="jeton" value="<?= $_SESSION['jeton'] ?>" />
        <p class="hidden">
            <label for="id">id</label><br>
            <input id="id" type="text" name="id" value="<?= $productData['id'] ?>">
        </p>
        <ol>
            <li>
                <label for="name">Nom</label><br>
                <input id="name" type="text" name="name" value="<?= $productData['name'] ?>" maxlength="40">
            </li>
            <li>
                <label for="category_id">Catégorie :</label><br>
                <select id="category_id" name="category_id">
                    <?php foreach ($categories as $category) : ?>
                        <option value="<?= $category['id'] ?>"><?= $category['name'] ?></option>
                    <?php endforeach; ?>
                </select>
            </li>
            <li>
                <label for="description">Description</label><br>
                <input id="description" type="text" name="description" value="<?= $productData['description'] ?>" maxlength="160" required autofocus>
            </li>
            <li>
                <label for="stock">Nb en stock</label><br>
                <input id="stock" type="number" name="stock" value="<?= $productData['stock'] ?>" maxlength="20" required autofocus>
            </li>
            <li>
                <label class="pricelabel" for="price">Prix/100g en euros ou prix unitaire</label><br>
                <input id="price" type="number" name="price" value="<?= $productData['price'] ?>" maxlength="20" required>
            </li>
        </ol>
    </fieldset>
    <fieldset>
        <button type=submit>Mettre à jour</button>
    </fieldset>

</form>

<br>
<h3>Changer l'image du produit</h3>
<br>
<p class="col-12">Nom de l'actuelle image : <?= $productData['image'] ?></p>
<br>

<form class="form2" method="POST" action="upload" enctype="multipart/form-data">
    <fieldset>
        <legend>Fichier image limité à 10MB:</legend>
        <input type="hidden" name="jeton" value="<?= $_SESSION['jeton'] ?>" />
        <ol>
            <li class="hidden">
                <label for="id">id</label><br>
                <input type="text" name="id" value="<?= $productData['id'] ?>">
            </li>
            <!-- On limite le fichier à 10000000 = 10MB-->
            <li class="hidden">
                <input type="hidden" name="MAX_FILE_SIZE" value="10000000">
            </li>
            <li>
                <input type="file" name="photoToUpload">
            </li>
        </ol>
    </fieldset>
    <fieldset>
        <button type=submit>Mettre à jour</button>
    </fieldset>

</form>