<h3>Ajouter un client</h3>

<form action="addcustomer" method="post">

    <input type="hidden" name="jeton" value="<?= $_SESSION['jeton'] ?>" />
    <p>
        <label for="lastname">Nom</label><br>
        <input type="text" name="lastname">
    </p>
    <p>
        <label for="firstname">Prénom</label><br>
        <input type="text" name="firstname">
    </p>
    <p>
        <label for="mail">Mail</label><br>
        <input type="email" name="mail">
    </p>
    <p>
        <label for="nickname">Pseudo</label><br>
        <input type="text" name="nickname">
    </p>
    <p>
        <label for="password">Mot de passe</label><br>
        <input type="text" name="password">
    </p>
    <p>
        <label for="adress">Adresse</label><br>
        <textarea name="adress"></textarea>
    </p>
    <p>
        <label for="cp">Code postal</label><br>
        <input type="number" name="cp">
    </p>
    <p>
        <label for="city">Ville</label><br>
        <input type="text" name="city">
    </p>
    <input type="submit" value="Enregistrer">
</form>