<h2>Liste des clients</h2>
<br>
<div class="row d-flex">
    <?php foreach ($customerModel as $customer) : ?>
        <div class="listingdiv col-md-6 col-sd-12">
            <p><?= $customer['firstname'] ?> <?= $customer['lastname'] ?></p>
            <ul>
                <li><?= $customer['adress'] ?></li>
                <li><?= $customer['cp'] ?></li>
                <li><?= $customer['city'] ?></li>
            </ul>
            <a class=button href="<?= $requestUrl; ?>/admin/editcustomer?customerid=<?= $customer['id'] . "&jeton=" . $_SESSION['jeton']; ?>">Éditer ce client</a>
            <form action="<?= $requestUrl; ?>/admin/listingcustomers" method="post" onsubmit="return confirm('Voulez-vous vraiment supprimer ce client ?');">
                <input type="hidden" name="jeton" value="<?= $_SESSION['jeton'] ?>" />
                <input type="text" class="hidden" name="customerid" value="<?= $customer['id'] ?>">
                <input class="deletebutton" type="submit" value="Supprimer ce client">
            </form>
            <br>
        </div>
        <br>
    <?php endforeach; ?>
</div>