<section id="connexion" class="col-lg-6 col-md-6 col-sd-12">

    <form class="form2 clientform" action="<?= $requestUrl ?>/customer/connection" method="post">
        <fieldset>
            <legend>Identifiez-vous :</legend>
            <input type="hidden" name="jeton" value="<?= $_SESSION['jeton'] ?>" />
            <ol>
                <li>
                    <label for=mail>Email</label>
                    <input id=mail name=login[usermail] type=email placeholder="exemple@domaine.com" maxlength="80" required autofocus>
                </li>
                <li>
                    <label for=pass>Password</label>
                    <input id=pass name="login[password]" maxlength="160" type=password required autofocus>
                </li>
                <!-- pas encore mis en place
                <a class=" action remind" href="<?= $requestUrl ?>/customer/forgotpassword">Mot de passe oublié ?</a>
                    -->
            </ol>
        </fieldset>

        <fieldset>
            <button type=submit>Se connecter</button>
        </fieldset>
    </form>

</section>

<section id="inscription" class="col-lg-6 col-md-6 col-sd-12">

    <h3>Nouveau client ?</h3>

    <a href="<?= $requestUrl ?>/customer/createaccount">Créer son compte</a>

</section>