<!--flexsider -->
<div class="slider col-lg-6 col-md-12">
	<div class="flexslider">
		<ul class="slides">
			<li>
				<img src="<?= $wwwUrl ?>/images/landscape-4026086_1920.jpg" alt="Photo du slider" />
			</li>
			<li>
				<img src="<?= $wwwUrl ?>/images/great-wall-3022907_1920.jpg" alt="Photo du slider" />
			</li>
			<li>
				<img src="<?= $wwwUrl ?>/images/great-wall-3675637_1920.jpg" alt="Photo du slider" />
			</li>
		</ul>
	</div>
</div>

<div id="presentation" class="slider col-lg-6 col-md-12 col-sd-12">
	<h3>Une nouvelle idée du thé</h3>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur massa enim, porttitor id nisi nec, tempus ornare neque. Sed nisl turpis, molestie in metus eget, scelerisque gravida mi. Vestibulum ut turpis id mi ornare placerat. In at rhoncus ligula. Ut vitae maximus erat, quis semper purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis velit leo, tincidunt in felis id, tincidunt sodales lorem. Quisque vulputate mauris mi, sit amet posuere mi iaculis non. Suspendisse potenti. Vivamus id ultricies elit. Duis auctor purus sapien.

		Nulla eget hendrerit erat. Suspendisse quis tempus dui. Fusce venenatis malesuada turpis, eget accumsan est tempor in. Nam quis leo efficitur est aliquet gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin nisi velit, vulputate non ultrices eu, lobortis non eros. Etiam tempus imperdiet volutpat. Ut lacus mauris, mollis non ligula at, euismod congue velit. Etiam pharetra dapibus bibendum. Mauris ullamcorper pulvinar velit, ac sagittis sapien dapibus at. Praesent mattis lacus nec neque scelerisque, a pellentesque purus consequat. Fusce condimentum dui vel volutpat efficitur.
	</p>
</div>


<p class="col-12">
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur massa enim, porttitor id nisi nec, tempus ornare neque. Sed nisl turpis, molestie in metus eget, scelerisque gravida mi. Vestibulum ut turpis id mi ornare placerat. In at rhoncus ligula. Ut vitae maximus erat, quis semper purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis velit leo, tincidunt in felis id, tincidunt sodales lorem. Quisque vulputate mauris mi, sit amet posuere mi iaculis non. Suspendisse potenti. Vivamus id ultricies elit. Duis auctor purus sapien.

	Nulla eget hendrerit erat. Suspendisse quis tempus dui. Nullam interdum viverra orci. Etiam posuere ultricies metus, ut consectetur ante feugiat sed. Ut libero mi, pharetra vel tristique sed, ornare et erat. Fusce venenatis malesuada turpis, eget accumsan est tempor in. Nam quis leo efficitur est aliquet gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin nisi velit, vulputate non ultrices eu, lobortis non eros. Etiam tempus imperdiet volutpat. Ut lacus mauris, mollis non ligula at, euismod congue velit. Etiam pharetra dapibus bibendum. Mauris ullamcorper pulvinar velit, ac sagittis sapien dapibus at. Praesent mattis lacus nec neque scelerisque, a pellentesque purus consequat. Fusce condimentum dui vel volutpat efficitur.
</p>


<p class="col-lg-8 col-md-6 col-sd-12">
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur massa enim, porttitor id nisi nec, tempus ornare neque. Sed nisl turpis, molestie in metus eget, scelerisque gravida mi. Vestibulum ut turpis id mi ornare placerat. In at rhoncus ligula. Ut vitae maximus erat, quis semper purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis velit leo, tincidunt in felis id, tincidunt sodales lorem. Quisque vulputate mauris mi, sit amet posuere mi iaculis non. Suspendisse potenti. Vivamus id ultricies elit. Duis auctor purus sapien.

	Nulla eget hendrerit erat. Suspendisse quis tempus dui. Curabitur efficitur tincidunt lorem et finibus. Donec pellentesque massa sit amet mi mattis, vel posuere sapien rhoncus. Nunc imperdiet vitae lorem posuere luctus. Duis porta porta metus in ultricies. Aliquam posuere elementum tincidunt. Quisque et est purus. Etiam eget commodo turpis.

	Etiam posuere ultricies metus, ut consectetur ante feugiat sed. Ut libero mi, pharetra vel tristique sed, ornare et erat. Fusce venenatis malesuada turpis, eget accumsan est tempor in. Nam quis leo efficitur est aliquet gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin nisi velit, vulputate non ultrices eu, lobortis non eros. Etiam tempus imperdiet volutpat. Ut lacus mauris, mollis non ligula at, euismod congue velit. Etiam pharetra dapibus bibendum. Mauris ullamcorper pulvinar velit, ac sagittis sapien dapibus at. Praesent mattis lacus nec neque scelerisque, a pellentesque purus consequat. Fusce condimentum dui vel volutpat efficitur.
</p>

<!--flexsider des thés-->
<div class="slider col-lg-4 col-md-6">
	<div class="flexslider">
		<ul class="slides">
			<?php foreach ($products as $product) : ?>
				<li>
					<img src="<?= $wwwUrl ?>/images/teapic/<?= $product['image'] ?>" alt="Photo produit du slider" />
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>