<h3 class="col-12">Ajouter une commande</h3>

<form class=form2 action="addorder" method="post" enctype="multipart/form-data">
    <fieldset>
        <legend>Client</legend>
        <input type="hidden" name="jeton" value="<?= $_SESSION['jeton'] ?>" />
        <ol>
            <li>
                <label for="customer_id">Nom Prénom</label><br>
                <select id="customer_id" name="customer_id" autofocus>
                    <?php foreach ($dataCustomers as $customer) : ?>
                        <option value="<?= $customer['id'] ?>"><?= $customer['firstname'] ?> <?= $customer['lastname'] ?></option>
                    <?php endforeach; ?>
                </select>
            </li>
        </ol>
    </fieldset>
    <!-- Partie généré en php, géré en js -->
    <fieldset>
        <legend>Produit(s) commandée(s)</legend>
        <ol>
            <?php foreach ($dataProducts as $product) : ?>
                <li>
                    <input class="checkbox" type="checkbox" name="product[]" value="<?= $product['id'] ?>"> <?= $product['name'] ?><br>
                    <input class="togglePost" disabled="disabled" type="number" name="product[]" placeholder="Quantité" min="1" max="1000" required><br>
                </li>
            <?php endforeach; ?>
        </ol>
    </fieldset>
    <fieldset>
        <button type=submit>Enregistrer</button>
    </fieldset>
</form>