<h3 class="col-12">Editer un client</h3>

<p class="col-12">Client n°<?= $customerData['id'] ?></p>

<form class=form2 action="<?= $requestUrl; ?>/admin/editcustomer" method="post">

    <fieldset>
        <legend>Identité</legend>
        <input type="hidden" name="jeton" value="<?= $_SESSION['jeton'] ?>" />
        <input class="hidden" type="text" name="id" value="<?= $customerData['id'] ?>">
        <ol>
            <li>
                <label for=lastname>Nom</label>
                <input id=lastname name=lastname type=text value="<?= $customerData['lastname'] ?>" maxlength="40" required autofocus>
            </li>
            <li>
                <label for=firstname>Prénom</label>
                <input id=firstname name=firstname type=text value="<?= $customerData['firstname'] ?>" maxlength="40" required>
            </li>
            <li>
                <label for=nickname>Pseudo</label>
                <input id=nickname name=nickname type=text value="<?= $customerData['nickname'] ?>" maxlength="20" required>
            </li>
            <li>
                <label for=mail>Email</label>
                <input id=mail name=mail type=email maxlength="80" value="<?= $customerData['mail'] ?>" required>
            </li>
        </ol>
    </fieldset>
    <fieldset>
        <legend>Adresse de livraison</legend>
        <ol>
            <li>
                <label for=adress>Adresse</label>
                <input id=adress name=adress type=text value="<?= $customerData['adress'] ?>" required>
            </li>
            <li>
                <label for=cp>CP</label>
                <input id=cp name=cp type=text value="<?= $customerData['cp'] ?>" maxlength="20" required>
            </li>
            <li>
                <label for=city>Ville</label>
                <input id=city name=city type=text value="<?= $customerData['city'] ?>" maxlength="80" required>
            </li>
        </ol>
    </fieldset>

    <fieldset>
        <button type=submit>Mettre à jour</button>
    </fieldset>
</form>

<h4 class="col-12">Changer le mot de passe</h4>

<form class=form2 action="<?= $requestUrl; ?>/admin/editcustomer" method="post">

    <input type="hidden" name="jeton" value="<?= $_SESSION['jeton'] ?>" />
    <p class="hidden">
        <input type="text" name="id" value="<?= $customerData['id'] ?>">
    </p>
    <fieldset>
        <ol>
            <li>
                <label for=password>Password</label>
                <input id=password name=password type=password required>
            </li>
        </ol>
    </fieldset>

    <fieldset>
        <button type=submit>Enregistrer</button>
    </fieldset>
</form>