<div id="product-box" class="row d-flex justify-content-center p-2">

<?php foreach ($products as $product): ?>

    <section class="product col-lg-4 col-md-6 col-sm-12 ">
        <h3 class="name<?=$product['id']?>"><?=$product['name']?></h3>
        <img class="img-responsive<?=$product['id']?>" src="<?= $wwwUrl ?>/images/teapic/<?=$product['image']?>" alt="<?$product['name']?>">
        <p class="price<?=$product['id']?>"><?=$product['price']?>€ les 100g.</p>
        <p><?=$product['description']?></p>

        <div class="control">  
            <input class='less' name='<?=$product['id']?>' type="button" value="-">
            <input class="quantity input-text qty" title="<?=$product['id']?>" type="number" name="qty" value="1" min="-1" readonly="readonly">
            <input class='more' name='<?=$product['id']?>' type="button" value="+">
        </div>            

        <a class="addProductToCart" href="#none" id="<?=$product['id']?>">Ajouter ce produit à mon panier<i class="fa fa-shopping-cart"></i>&nbsp;</a>
    </section>

<?php endforeach; ?>
<br>
<br>

</div>

